Controllers/ConsumersController.cs
using DayPass.Data;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using ValueCards.Models;
using ValueCards.Services;

namespace ValueCards.Controllers
{
  [Authorize(Policy = CookieAuthenticationDefaults.AuthenticationScheme)]
  public class ConsumersController : Controller
  {
    private readonly IConsumerService _consumerService;
    private readonly ILogger<ConsumersController> _logger;
    private readonly IApiClient _apiClient;
    private readonly ApplicationDBContext _dbContext;
    private readonly IConsumerRepository _repository;
    public ConsumersController(IConsumerService consumerService,
                               IConsumerRepository repository,
                              ILogger<ConsumersController> logger,
                               ApplicationDBContext dBContext)
    {
      _consumerService = consumerService ?? throw new ArgumentNullException(nameof(consumerService));
      _logger = logger ?? throw new ArgumentNullException(nameof(logger));
      _dbContext = dBContext ?? throw new ArgumentNullException((nameof(dBContext)));
      _repository = repository ?? throw new ArgumentNullException(nameof(repository));
     }

    public IActionResult Index()
    {
      return View();
    }

    public async Task<IActionResult> Read([DataSourceRequest]DataSourceRequest request)
    {
      return Json(_consumerService.Read(request));
    }

        public IActionResult DisplayPass(string id)
        {
        
            return View("PassInfo"); 
        }

        [AllowAnonymous]
        [Route("consumers/passinfo/{passId}")]
        [HttpGet]
        public IActionResult PassInfo(string passId)
        {
            // ... (Your logic to fetch data) ...
            var passData = new DayPassModel
            {
                CEPAN = passId,
                EndDate = DateTime.Now,
                NumberofDaysRemaining = "45"
            };
            return Json(passData); 
        }

        public IActionResult Topup(string id, [FromServices] IConsumerRepository repository)
        {
            ArgumentNullException.ThrowIfNull(id);

            var item = repository.Consumers
            .Where(i => i.CEPAN.Contains(id))
            .Select(i => new ConsumerTopupModel
            {
                Id = i.CTRACK,
                CEPAN = i.CEPAN,
                StartDate = i.DTCREAT,
                EndDate = i.DTEXPIRE,
                Amount = i.DAYVALD,
            })
        .FirstOrDefault();

            if (item == null)
                return NotFound();

            return View(item);
        }

        public IActionResult PassHistory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            ViewBag.CEPAN = id; 
            return View();      
        }

        public IActionResult PassHistoryData([DataSourceRequest] DataSourceRequest request, string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest("Missing id");

            var query =  from m in _dbContext.UDBMOVEMENT
                         join s in _dbContext.DEVINFO on m.SDEVICE equals s.SROUTINSTANCEID
                         into stationGroup from s in stationGroup.DefaultIfEmpty() // left join
                         where m.CEPAN.Contains(id)
            select new HistoryModel
           {
               Id = m.LGLOBALID.ToString(),
               CEPAN = m.CEPAN,
               ActionDate = m.TACTIONTIME.Value.ToString("G"),
               StationName = s.CDESC ?? ""
            };
            var result = query.ToList().ToDataSourceResult(request);
            return Json(result);


        }



        [HttpPost]
    public async Task<IActionResult> Topup(string id, ConsumerTopupModel model)
    {
      if(model == null)
        throw new ArgumentNullException(nameof(model));

      if (string.IsNullOrEmpty(id))
        return BadRequest();


      try
      {
        
        var entityToUpdate =  _dbContext.CONGBARCODE.SingleOrDefault(e=>e.CEPAN.Contains(id));
        if (entityToUpdate == null)
                return BadRequest();
       var diffAmount = entityToUpdate.MAXEXIT - model.Amount;
       entityToUpdate.DAYVALD = model.Amount;
       entityToUpdate.NBEXIT = diffAmount;
       entityToUpdate.DTEXPIRE = model.EndDate;
       await _dbContext.SaveChangesAsync();
       _repository.UpdateValue(id,model.Amount,model.EndDate);
       return Created("", model);
      }
      catch (ApiErrorException aex)
      {
        return new ObjectResult(new { message = aex.Message }) { StatusCode = (int)aex.StutusCode };
      }
      catch (Exception ex)
      {
        _logger.LogError(ex.ToString());
        throw;
      }
    }
  }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - DayPass </title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jszip/2.4.0/jszip.js"></script>

  <link rel="stylesheet"
        href="https://kendo.cdn.telerik.com/2020.3.1021/styles/kendo.common-material.min.css"
        asp-fallback-href="~/lib/kendo-ui/styles/kendo.common-material.min.css"
        asp-fallback-test-class="k-common-test-class"
        asp-fallback-test-property="opacity" asp-fallback-test-value="0" />

  <link rel="stylesheet"
        href="https://kendo.cdn.telerik.com/2020.3.1021/styles/kendo.material.min.css"
        asp-fallback-href="~/lib/kendo-ui/styles/kendo.material.min.css"
        asp-fallback-test-class="k-theme-test-class"
        asp-fallback-test-property="opacity" asp-fallback-test-value="0" />

  <script src="https://kendo.cdn.telerik.com/2020.3.1021/js/kendo.all.min.js"
          asp-fallback-src="~/lib/kendo-ui/js/kendo.all.min.js"
          asp-fallback-test="window.kendo">
  </script>
  <script src="https://kendo.cdn.telerik.com/2020.3.1021/js/kendo.aspnetmvc.min.js"
          asp-fallback-src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"
          asp-fallback-test="kendo.data.transports['aspnetmvc-ajax']">
  </script>

  <link rel="stylesheet" href="~/css/site.css" />

  @RenderSection("Styles", required: false)
</head>
<body>
  <header>
   @if (!(ViewBag.HideHeader ?? false)) // Check if HideHeader is true or null/false
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: #114176">
                <a class="navbar-brand" asp-area="" asp-controller="Consumers" asp-action="Index">Day Pass Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Consumers" asp-action="Index">Cards</a>
                        </li>
                      @*  <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </nav>
        }
    </header>
  <div class="container-fluid">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container-fluid">
      &copy; 205 - Day Pass Management Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>

  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @RenderSection("Scripts", required: false)
</body>
</html>